site: colinholzman
url: https://colinholzman.xyz
title: Colin Holzman
description: My personal blog.
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: Colin Holzman
  avatar:
  email: me@colinholzman.xyz
  url: #yoururl
permalink: pretty

markdown: kramdown

# change destination for gh pages
destination: docs

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  - gallery/
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-pig

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

galleries:
  - 
    path: gallery
    name: gallery